### ISSUE TITLE
Support 1.19.2

### ISSUE THREAD

**Issue by IF-desu** [RacoonDog/Electron#1]
The latest version of this mod(The only downloadable）can not run in 1.19.2
Please add the version for 1.19.2

**Comment by crosby-moe** [comment]
For maintainability reasons, Electron will only ever support the latest version supported by Meteor client. In this case, 1.19.3

**Comment by IF-desu** [comment]
Meteor clinet now still support 1.19.2(

**Comment by crosby-moe** [comment]
> Meteor clinet now still support 1.19.2(

electron makes very big changes to meteor itself in a way that is hard to maintain
i wont support 1.19.2
end of story

**Comment by IF-desu** [comment]
Okay,I'll try 1.19.3,although many mods still doesn't support 1.19.3(
